### ISSUE TITLE
MK3 teensy calibration code occasionally stuck in loop

### ISSUE THREAD

**Issue by navdotnetreqs** [ycheng517/ar4_ros_driver#17]
Hi,

I've found that sometimes the calibration fails and one (or more) joints do not reach the goal. In these cases the teensy code gets stuck at the loop "while (!restPosReached)" in the calibration code, and won't resume operation without a reboot.

Since the MK3 already has a push button, the code could implement an ISR interrupt, setting a flag "x" to abort whatever loop is going on for cases like this.

I will investigate this further, but here are some preliminary findings (running the code directly from serial, not using ros), and just calling "JC".

The arm is reaching for:
{75556,   23333,  49444,   89600,   11477,  40000};

One time it was stuck, I debugged the values to
75653, 22481, 49547, 89507, 11242, 40101, where we can see values are still off, but the arm has stopped moving.
Another time stuck at
75653, 23249, 49546, 44967, 11432, 40099, where D is very far off (obviously this was very visible on the arm as well).

And now starting ros2 it has happened for the last joint, which stopped ca. 90 degrees before the goal.

**Comment by navdotnetreqs** [comment]
Might be related to faulty encoder signals, this has happened less frequently after installing small caps at the end of the encoder wires.

**Comment by navdotnetreqs** [comment]
It still happens. What is weird is that when it happens, giving the joint a physical nudge resumes it's movement and then it goes all the way fine.

**Comment by ycheng517** [comment]
Thanks for reporting the issue, will try implement a timeout mechanism for the calibration process, so that on the ROS side we can detect the failure and handle it accordingly.

**Comment by ycheng517** [comment]
implemented https://github.com/ycheng517/ar4_ros_driver/pull/22 which can help

**Comment by ycheng517** [comment]
I experienced some inconsistency in the robot returning to the home position at the end of the calibration routine as well, and this commit seems to help: https://github.com/ycheng517/ar4_ros_driver/commit/cbd5ef4b0914bb656a27ac53ff7b962b47f2505b 
I can now calibrate successfully 6x in a row whereas before I would see a failure every 2-3 attempts.

**Comment by ycheng517** [comment]
switching limit swtiches to bounce2 in https://github.com/ycheng517/ar4_ros_driver/pull/28 should've also mitigated this issue. Closing due to staleness.
